---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: 현재 릴리스에는 ONTAP Select 에만 적용되는 여러 가지 새로운 기능 및 개선 사항이 포함되어 있습니다. 
---
= ONTAP Select 의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 의 지원되는 버전에서 제공되는 새로운 기능과 향상된 기능에 대해 알아보세요.



== ONTAP Select 9.16.1

ONTAP Select 9.16.1에는 여러 가지 새로운 기능과 개선 사항이 포함되어 있습니다.

업데이트된 NetApp 라이선스 파일 지원:: ONTAP Select 9.16.1부터 NetApp 라이선스 파일(NLF) 지원이 업데이트되었습니다. 새로운 NLF 형식에는 ARP, ONTAP S3 및 S3 SnapMirror 기능에 대한 라이선스가 포함됩니다. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["자세히 알아보기"] .
+
--
새로운 ONTAP Select 9.16.1 Deploy의 경우 새로운 NLF 형식이 자동으로 적용됩니다. 기존 ONTAP Select Deploy를 9.16.1로 업그레이드하면 새로운 NLF 형식이 적용되지 않습니다. ARP, ONTAP S3 및 S3 SnapMirror 기능 라이선스를 받으려면 업그레이드 후 업데이트된 NLF를 다운로드해야 합니다. ONTAP Select 9.15.1 이하 버전으로 되돌리는 경우 업그레이드 전에 사용하던 기능 라이선스를 다시 설치해야 합니다.

--
자율형 랜섬웨어 보호 지원:: ONTAP Select 9.16.1은 자율 랜섬웨어 보호(ARP)를 지원합니다. ONTAP Select 9.16.1은 ARP 수동 업데이트만 지원하며 자동 업데이트는 지원하지 않습니다. ARP 기능 라이선스는 ONTAP Select 9.16.1의 NLF(네트워크 파일 시스템)에 포함되어 있습니다. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["자세히 알아보기"] .
향상된 VMware ESXi 지원:: ONTAP Select 9.16.1에는 VMware ESXi 8.0 U3에 대한 지원이 포함되어 있습니다.
업데이트된 KVM 하이퍼바이저 지원:: ONTAP Select 9.16.1부터 Red Hat Enterprise Linux(RHEL) 9.5 및 Rocky Linux 9.5에서 커널 기반 가상 머신(KVM) 하이퍼바이저가 지원됩니다.




== ONTAP Select 9.15.1

ONTAP Select 9.15.1에는 여러 가지 새로운 기능과 개선 사항이 포함되어 있습니다.

업데이트된 KVM 하이퍼바이저 지원:: ONTAP Select 9.15.1부터 RHEL 9.4 및 Rocky Linux 9.4에서 커널 기반 가상 머신(KVM) 하이퍼바이저가 지원됩니다.
클러스터 확장 및 축소 지원:: ONTAP Select 9.15.1부터 클러스터 확장 및 축소가 지원됩니다.
+
--
* 6노드에서 8노드 클러스터로 클러스터 확장
+
클러스터 확장 기능을 사용하여 클러스터 크기를 6노드 클러스터에서 8노드 클러스터로 늘릴 수 있습니다. 1노드, 2노드 또는 4노드 클러스터에서 6노드 또는 8노드 클러스터로의 클러스터 확장은 현재 지원되지 않습니다. link:task_cluster_expansion_contraction.html#expand-the-cluster["자세히 알아보기"] .

* 클러스터 수축 8노드에서 6노드 클러스터로
+
클러스터 축소 기능을 사용하여 클러스터 크기를 8노드 클러스터에서 6노드 클러스터로 줄일 수 있습니다. 6노드 또는 8노드 클러스터에서 1노드, 2노드 또는 4노드 클러스터로의 클러스터 축소는 현재 지원되지 않습니다. link:task_cluster_expansion_contraction.html#contract-the-cluster["자세히 알아보기"] .



--



NOTE: 클러스터 확장 및 축소에 대한 지원은 ESX 클러스터에만 국한됩니다.



== ONTAP Select 9.14.1

ONTAP Select 9.14.1에는 여러 가지 새로운 기능과 개선 사항이 포함되어 있습니다.

KVM 하이퍼바이저 지원:: ONTAP Select 9.14.1부터 KVM 하이퍼바이저 지원이 다시 시작되었습니다. 이전에는 ONTAP Select 9.10.1에서 KVM 하이퍼바이저에 새 클러스터를 배포하는 기능이 제거되었고, ONTAP Select Select 9.11.1에서는 오프라인으로 전환하거나 삭제하는 기능을 제외한 기존 KVM 클러스터 및 호스트 관리 기능이 제거되었습니다.
VMware vCenter 플러그인 배포가 더 이상 지원되지 않습니다.:: ONTAP Select 9.14.1부터 Deploy VMware vCenter 플러그인이 더 이상 지원되지 않습니다.
업데이트된 ONTAP Select Deploy 지원:: ONTAP Select Deploy 9.14.1P2보다 이전 버전을 사용 중이시라면, 가능한 한 빨리 ONTAP Select Deploy 9.14.1P2로 업그레이드하시기 바랍니다. 자세한 내용은 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1 릴리스 노트"^] .
향상된 VMware ESXi 지원:: ONTAP Select 9.14.1에는 VMware ESXi 8.0 U2에 대한 지원이 포함되어 있습니다.




== ONTAP Select 9.13.1

ONTAP Select 9.13.1에는 여러 가지 새로운 기능과 개선 사항이 포함되어 있습니다.

TCP를 통한 NVMe 지원:: ONTAP Select 9.13.1로 업그레이드하는 경우 NVMe over TCP를 지원하는 새 라이선스가 필요합니다. 이 라이선스는 ONTAP Select 9.13.1 버전에서 처음 배포할 때 자동으로 포함됩니다.
업데이트된 VMware ESXi 지원:: ONTAP 9.13.1부터 VMware ESXi 8.0.1 GA(빌드 20513097)는 하드웨어 버전 4 이상에서 지원됩니다.
업데이트된 ONTAP Select Deploy 지원:: 2024년 4월부터 ONTAP Select Deploy 9.13.1은 NetApp 지원 사이트에서 더 이상 제공되지 않습니다. ONTAP Select Deploy 9.13.1을 사용 중이시라면 최대한 빨리 ONTAP Select Deploy 9.14.1P2로 업그레이드하시기 바랍니다. 자세한 내용은 다음을 참조하십시오. link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1 릴리스 노트"^] .




== ONTAP Select 9.12.1

ONTAP Select 9.12.1은 핵심 ONTAP 제품의 현재 릴리스에 포함된 대부분의 새로운 기능을 활용합니다. ONTAP Select 에만 적용되는 새로운 기능이나 개선 사항은 포함되어 있지 않습니다.

2024년 4월부터 ONTAP Select Deploy 9.12.1은 NetApp 지원 사이트에서 더 이상 제공되지 않습니다. ONTAP Select Deploy 9.12.1을 사용 중이시라면 최대한 빨리 ONTAP Select Deploy 9.14.1P2로 업그레이드하시기 바랍니다. 자세한 내용은 다음을 참조하십시오. link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1 릴리스 노트"^] .



== ONTAP Select 9.11.1

ONTAP Select 9.11.1에는 여러 가지 새로운 기능과 개선 사항이 포함되어 있습니다.

향상된 VMware ESXi 지원:: ONTAP Select 9.11.1에는 VMware ESXi 7.0 U3C에 대한 지원이 포함되어 있습니다.
VMware NSX-T 지원:: ONTAP Select 9.10.1 이상 릴리스는 VMware NSX-T 버전 3.1.2에 적합합니다. OVA 파일과 ONTAP Select Deploy 관리 유틸리티를 사용하여 배포된 ONTAP Select 단일 노드 클러스터와 함께 NSX-T를 사용할 때 기능적 문제나 결함은 없습니다. 그러나 ONTAP Select 다중 노드 클러스터와 함께 NSX-T를 사용할 경우 ONTAP Select 9.11.1에 대한 다음 제한 사항에 유의해야 합니다.
+
--
* 네트워크 연결 검사기
+
Deploy CLI를 통해 사용할 수 있는 네트워크 연결 검사기는 NSX-T 기반 네트워크에 대해 실행하면 실패합니다.



--
KVM 하이퍼바이저는 더 이상 지원되지 않습니다.::
+
--
* ONTAP Select 9.10.1부터 KVM 하이퍼바이저에 새 클러스터를 더 이상 배포할 수 없습니다.
* ONTAP Select 9.11.1부터 기존 KVM 클러스터와 호스트에 대한 모든 관리 기능을 더 이상 사용할 수 없으며, 오프라인으로 전환 및 삭제 기능만 사용할 수 있습니다.
+
NetApp 고객이 ONTAP Select for KVM에서 ONTAP Select for ESXi를 포함한 다른 ONTAP 플랫폼으로의 전체 데이터 마이그레이션을 계획하고 실행할 것을 강력히 권장합니다. 자세한 내용은  https://mysupport.netapp.com/info/communications/ECMLP2877451.html["EOA 공지"^]



--




== ONTAP Select 9.10.1

ONTAP Select 9.10.1에는 여러 가지 새로운 기능과 개선 사항이 포함되어 있습니다.

VMware NSX-T 지원:: ONTAP Select 9.10.1은 VMware NSX-T 버전 3.1.2에 적합합니다. OVA 파일과 ONTAP Select Deploy 관리 유틸리티를 사용하여 배포된 ONTAP Select 단일 노드 클러스터와 함께 NSX-T를 사용할 때 기능적 문제나 결함은 없습니다 . 그러나 ONTAP Select 다중 노드 클러스터와 함께 NSX-T를 사용할 경우 다음 요구 사항 및 제한 사항에 유의해야 합니다.
+
--
* 클러스터 MTU
+
추가 오버헤드를 고려하여 클러스터를 배포하기 전에 클러스터 MTU 크기를 8800으로 수동으로 조정해야 합니다. VMware 지침에 따르면 NSX-T를 사용할 때 200바이트 버퍼를 허용합니다.

* 네트워크 4x10Gb 구성
+
4개의 NIC로 구성된 VMware ESXi 호스트에 ONTAP Select 배포하는 경우, 배포 유틸리티는 내부 트래픽을 두 개의 다른 포트 그룹으로, 외부 트래픽을 두 개의 다른 포트 그룹으로 분할하는 모범 사례를 따르도록 안내합니다. 그러나 오버레이 네트워크를 사용하는 경우 이 구성은 효과가 없으므로 권장 사항을 무시해야 합니다. 이 경우, 내부 포트 그룹과 외부 포트 그룹을 각각 하나씩만 사용해야 합니다.

* 네트워크 연결 검사기
+
Deploy CLI를 통해 사용할 수 있는 네트워크 연결 검사기는 NSX-T 기반 네트워크에 대해 실행하면 실패합니다.



--
KVM 하이퍼바이저는 더 이상 지원되지 않습니다.:: ONTAP Select 9.10.1부터는 KVM 하이퍼바이저에 새 클러스터를 배포할 수 없습니다. 하지만 이전 릴리스의 클러스터를 9.10.1로 업그레이드하는 경우에는 Deploy 유틸리티를 사용하여 클러스터를 관리할 수 있습니다.




== ONTAP Select 9.9.1

ONTAP Select 9.9.1에는 여러 가지 새로운 기능과 개선 사항이 포함되어 있습니다.

프로세서 제품군 지원:: ONTAP Select 9.9.1부터 ONTAP Select 에서는 Intel Xeon Sandy Bridge 이상의 CPU 모델만 지원됩니다.
업데이트된 VMware ESXi 지원:: ONTAP Select 9.9.1에서는 VMware ESXi에 대한 지원이 강화되었습니다. 이제 다음 릴리스가 지원됩니다.
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

ONTAP Select 9.8에는 여러 가지 새로운 기능과 변경된 기능이 포함되었습니다.

고속 인터페이스:: 고속 인터페이스 기능은 25G(25GbE) 및 40G(40GbE) 옵션을 제공하여 네트워크 연결을 향상시킵니다. 이러한 고속 환경에서 최상의 성능을 얻으려면 ONTAP Select 설명서에 설명된 포트 매핑 구성 관련 모범 사례를 따라야 합니다.
업데이트된 VMware ESXi 지원:: ONTAP Select 9.8에는 VMware ESXi 지원과 관련하여 두 가지 변경 사항이 있습니다.
+
--
* ESXi 7.0이 지원됩니다(GA 빌드 15843807 이상)
* ESXi 6.0은 더 이상 지원되지 않습니다.


--

