---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: 명령줄 인터페이스를 사용하여 기존 Deploy 유틸리티 가상 머신을 그대로 업그레이드할 수 있습니다. 
---
= ONTAP Select Deploy 인스턴스 업그레이드
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
명령줄 인터페이스를 사용하여 기존 Deploy 유틸리티 가상 머신을 그대로 업그레이드할 수 있습니다.



== 시작하기 전에

업그레이드 중에 Deploy를 사용하여 다른 작업을 수행하지 않도록 하십시오. Deploy 유틸리티 업그레이드에 대한 정보 및 제한 사항은 최신 릴리스 노트를 참조하십시오.


NOTE: ONTAP Select Deploy 관리 유틸리티의 이전 버전이 설치되어 있는 경우 최신 릴리스로 업그레이드해야 합니다. ONTAP Select 노드와 ONTAP Select Deploy 구성 요소는 독립적으로 업그레이드됩니다. link:concept_adm_upgrading_nodes.html["ONTAP Select 노드 업그레이드"^] 자세한 내용은.



== 업그레이드 패키지 다운로드

업그레이드 프로세스를 시작하려면 NetApp 지원 사이트에서 해당 Deploy 가상 머신 업그레이드 파일을 다운로드해야 합니다. 업그레이드 패키지는 단일 압축 파일 형식으로 제공됩니다.

.단계
. 웹 브라우저를 사용하여 link:https://mysupport.netapp.com/site/["NetApp 지원 사이트"^]에 액세스하고 Downloads 메뉴에서 *Downloads*를 선택합니다.
. 아래로 스크롤하여 *ONTAP Select Deploy Upgrade*를 선택하십시오.
. 업그레이드 패키지의 원하는 릴리스를 선택합니다.
. 최종 사용자 라이선스 계약(EULA)을 검토하고 *동의 및 계속*을 선택하세요.
. 환경에 필요한 모든 프롬프트에 응답하여 적절한 패키지를 선택하고 다운로드합니다.




== Deploy 가상 머신에 패키지를 업로드하세요.

업그레이드 패키지를 획득한 후에는 해당 파일을 Deploy 가상 머신에 업로드해야 합니다.

.시작하기 전에
업그레이드 파일이 로컬 워크스테이션에 있어야 합니다. 또한 관리자 사용자 계정의 암호도 알아야 합니다.

.이 작업 정보
이 작업에서는 가상 머신 배포에 파일을 업로드하는 한 가지 방법을 설명합니다. 사용자 환경에 더 적합한 다른 옵션이 있을 수 있습니다.

.단계
. 로컬 워크스테이션의 명령 셸에서 scp 유틸리티를 사용하여 이미지 파일을 Deploy 가상 머신에 업로드합니다.
+
예

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.결과
업그레이드 파일은 관리자의 홈 디렉토리에 저장됩니다.



== 업그레이드 패키지를 적용합니다

업그레이드 파일을 Deploy 가상 머신에 업로드한 후 업그레이드를 적용할 수 있습니다.

.시작하기 전에
Deploy 유틸리티 가상 머신에서 업그레이드 파일이 저장된 디렉토리를 알고 있어야 합니다. 또한 업그레이드가 진행되는 동안 Deploy를 사용하여 다른 작업을 수행하지 않도록 해야 합니다.

.단계
. 관리자 계정으로 SSH를 사용하여 Deploy 유틸리티 CLI에 Sign in .
. 적절한 디렉토리 경로와 파일 이름을 사용하여 업그레이드를 수행합니다.
+
`deploy upgrade -package-path FILEPATH`

+
예

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.당신이 완료한 후
업그레이드 절차가 완료되기 전에 Deploy 가상 머신 구성의 백업을 생성하라는 메시지가 표시됩니다. 또한 새로 생성된 Deploy 페이지를 볼 수 있도록 브라우저 캐시를 지워야 합니다.
